name: Hello User
description: 'Says hello to the user or the world'
  inputs:
    who-to-greet:
      description: Who to greet in the log
      required: true
      default: 'World'
  outputs:
    time:
      description: Time that this was run
  runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
      - ${{ inputs.who-to-greet}}
